services:
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_DB=xpensedb'
      - 'POSTGRES_PASSWORD=admin'
      - 'POSTGRES_USER=admin'
    ports:
      - '5432:5432'
